image: docker:latest

services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

stages:
- build
- package
- deploy

ui-build:
  image: cithub/angular
  stage: build
  script: "ng build --prod"
  artifacts:
    paths:
    - dist

docker-build:
  image: docker:stable
  services:
  - docker:dind
  stage: package
  before_script:
  - export DOCKER_HOST="tcp://docker:2375"
  - docker info
  script:
  - docker build -t registry.gitlab.com/channelit/cit-challenge-ui .
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker push registry.gitlab.com/channelit/cit-challenge-ui

deploy_dev:
  stage: deploy
  image: registry.gitlab.com/channelit/cit-challenge-ui
  environment:
    name: develop
  script:
  - apk add --no-cache curl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  - kubectl config set-cluster nosebit --server="$KUBE_URL" --insecure-skip-tls-verify=true
  - kubectl config set-credentials admin --username="$KUBE_USER" --password="$KUBE_PASSWORD"
  - kubectl config set-context default --cluster=nosebit --user=admin
  - kubectl config use-context default
  - 'printf "apiVersion: v1\nkind: Secret\n$(kubectl create secret docker-registry gitlab-registry --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USER --docker-password=$CI_REGISTRY_PASSWORD --docker-email=$GITLAB_USER_EMAIL -o yaml --dry-run)" | kubectl apply -f -'
  - sed 's/_APP_NAME_/'"$CI_PROJECT_NAME"'/g; s/_VERSION_/'"$CI_COMMIT_SHA"'/g' deployment.yml > kubernetes.yml;
  - kubectl apply -f kubernetes.yml
  only:
  - master
