image: docker:latest

services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

stages:
- build
- package
#- deploy

ui-build:
  image: cithub/angular
  stage: build
  script:
    - npm install
    - ng build --prod
  artifacts:
    paths:
    - dist

docker-build:
  image: docker:stable
  services:
  - docker:dind
  stage: package
  before_script:
  - export DOCKER_HOST="tcp://docker:2375"
  - docker info
  script:
  - docker build -t registry.gitlab.com/channelit/cit-challenge-ui .
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker push registry.gitlab.com/channelit/cit-challenge-ui
